### ISSUE TITLE
Number of decimals different from reg divs and combined divs

### ISSUE THREAD

**Issue by Dragonblaze562** [kryptoklob/Zethr-Bug-Bounty#10]
![image](https://user-images.githubusercontent.com/41987823/43509149-ac43554c-9526-11e8-9ffa-6dc2ef671066.png)

The longer version I think would be nice for the most. Hopefully you can see in the attached pic. Thanks. 
![image](https://user-images.githubusercontent.com/41987823/43509209-d66e6c12-9526-11e8-85c3-1b633655a5fb.png)

**Comment by kryptoklob-deprecated** [comment]
Fixed
