### ISSUE TITLE
Update metadata for social Media to create post previews

### ISSUE THREAD

**Issue by planet-rayden** [kryptoklob/Zethr-Bug-Bounty#12]
Just wanted to post about zethr on my facebook, but the preview just shows..nothing at all :D Maybe you can update the page and ass some metatags etc, so Facebook & Co can create previews

![image](https://user-images.githubusercontent.com/37696287/43512229-cc48ea56-957a-11e8-9980-f148a360d4a0.png)

**Comment by kryptoklob-deprecated** [comment]
done!
