### ISSUE TITLE
Critical Withdraw bug, allows draining of contract

### ISSUE THREAD

**Issue by Joking313** [kryptoklob/Zethr-Bug-Bounty#2]
In the withdraw function, which takes [address _recipient] as a parameter and then sets it to, address _customerAddress = _recipient; however the myDividends(false) function after that takes msg.sender as the one whose dividends should be withdrawn, then updates the payouts of _customerAddress instead of msg.sender, here likes the issue as the dividends would never decrease for the msg.sender allowing him to withdraw his dividends infinitely and the payouts would underflow for the _customerAddress giving him infinite dividends.

**Comment by Joking313** [comment]
Also my address is 0x98081ce968E5643c15de9C024dE96b18BE8e5aCe

**Comment by Joking313** [comment]
payment confirmed https://etherscan.io/tx/0xeb2db971c0e6c0923c71020a743cc5f17fa12ece8be6ce37101ba2e240323d7d

**Comment by MoonMissionControl** [comment]
Same bug is in transfer. Fixing it.
