### ISSUE TITLE
Hell page momentarily shows negative time left

### ISSUE THREAD

**Issue by coduggan** [kryptoklob/Zethr-Bug-Bounty#3]
When Hell page loads, while the balance is loading, the time remaining shows a negative time like -3 -50 -1.

![screen shot 2018-07-30 at 7 48 49 pm](https://user-images.githubusercontent.com/1014205/43434716-c62b883a-9431-11e8-80cc-ee88f403e808.png)

**Comment by kryptoklob-deprecated** [comment]
Fixing in latest deployment, thanks!
