### ISSUE TITLE
Rolls not showing up

### ISSUE THREAD

**Issue by newblockorg** [kryptoklob/Zethr-Bug-Bounty#4]
1. I pressed roll, the metamask pulled an exception error
2. i lowered the bet amount, metamask was ok with it
3. I rolled and it got confirmed.
4. nothing shows up on UI
5. UI says finish roll or activate roll something like that
6. I sent another transaction to finish rool, it went through, still cant see rolls.

**Comment by kryptoklob-deprecated** [comment]
@louiesun what browser are you using?

**Comment by newblockorg** [comment]
firefox

**Comment by bootstrapJSPlus** [comment]
Fixed

**Comment by kryptoklob-deprecated** [comment]
Fixed
